# Generated by Django 6.0.7 on 2026-07-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('task', models.CharField(choices=[('не выполнено❌', 'не выполнено❌'), ('в процессе⌛', 'в процессе⌛'), ('выполнено✅', 'выполнено✅')], max_length=100)),
                ('problem', models.TextField(blank=True)),
                ('screenshots', models.FileField(upload_to='todo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
