# Generated by Django 6.0.7 on 2026-07-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='blog/')),
                ('description', models.TextField(blank=True)),
                ('person_name', models.CharField(default='Иванов Иван', max_length=20)),
                ('url_blog', models.URLField(blank=True)),
            ],
        ),
    ]
