# Generated by Django 6.0.7 on 2026-07-28 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('person', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StateNumberCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_car', models.CharField(default='0_KG_____', max_length=100)),
                ('car_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.car')),
            ],
        ),
    ]
