# Generated by Django 6.0.7 on 2026-07-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_commentcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='person',
            field=models.CharField(max_length=50, null=True, verbose_name='укажите фио покупателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='укажите название машины'),
        ),
    ]
