# Generated by Django 6.0.7 on 2026-07-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_car_person_alter_car_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'машину', 'verbose_name_plural': 'машины'},
        ),
        migrations.AddField(
            model_name='car',
            name='categories',
            field=models.ManyToManyField(null=True, to='products.categorycar'),
        ),
    ]
